AllCops:
  TargetRubyVersion: "2.5.0"

Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Max: 36
Metrics/BlockLength:
  Max: 40
Metrics/ClassLength:
  Max: 189
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 45
Metrics/PerceivedComplexity:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 19
Metrics/ParameterLists:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-exporters-datadog.rb"
Style/ModuleFunction:
  Enabled: false
