AllCops:
  TargetRubyVersion: "2.5.0"

Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Max: 32
Metrics/BlockLength:
  Max: 31
Metrics/ClassLength:
  Max: 125
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/PerceivedComplexity:
  Max: 10
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/ParameterLists:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-exporters-datadog.rb"
Style/ModuleFunction:
  Enabled: false
