AllCops:
  TargetRubyVersion: "2.5.0"

Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Max: 35
Metrics/BlockLength:
  Max: 38
Metrics/ClassLength:
  Max: 161
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 43
Metrics/PerceivedComplexity:
  Max: 16
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/ParameterLists:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/opentelemetry-exporters-datadog.rb"
Style/ModuleFunction:
  Enabled: false
