version: 2.1
executors:
  ruby25:
    docker:
      - image: "circleci/ruby:2.5-buster"
  ruby26:
    docker:
      - image: "circleci/ruby:2.6-buster"
  ruby27:
    docker:
      - image: "circleci/ruby:2.7-buster"
  jruby:
    docker:
      - image: "circleci/jruby:latest"
    environment:
      JRUBY_OPTS: "--debug"
  jruby92:
    docker:
      - image: "circleci/jruby:9.2.8-jre"
    environment:
      JRUBY_OPTS: "--debug"

commands:
  rake-test:
    steps:
      - checkout
      - run:
          name: Bundle (Datadog)
          command: "gem install --no-document bundler && bundle install --jobs=3 --retry=3"
      - run:
          name: CI (Datadog)
          command: "bundle exec rake"

jobs:
  test-ruby25:
    executor: ruby25
    steps:
      - rake-test
  test-ruby26:
    executor: ruby26
    steps:
      - rake-test
  test-ruby27:
    executor: ruby27
    steps:
      - rake-test
  test-jruby:
    executor: jruby
    steps:
      - rake-test
  test-jruby92:
    executor: jruby92
    steps:
      - rake-test
  "deploy release":
    executor: ruby27
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            apt-get -y -qq update
            apt-get -y -qq install awscli
      - run:
          name: Install gem dependencies
          command: bundle install
      - run:
          name: Upload release Gem and rebuild index
          command: S3_DIR=otel-release bundle exec rake release:gem
      - store_artifacts:
          path: pkg/
          destination: gem

workflows:
  version: 2
  builds:
    jobs:
      - test-ruby25:
          filters:
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
      - test-ruby26:
          filters:
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
      - test-ruby27:
          filters:
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
      - test-jruby:
          filters:
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
      - test-jruby92:
          filters:
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
      # - "deploy release":
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v\d+(\.\d+){0,3}(\.(alpha|beta|rc)\d+)?$/        
      #     requires:
      #       - test-ruby25
      #       - test-ruby26
      #       - test-ruby27
      #       - test-jruby
      #       - test-jruby92
